import { PricingPlan } from "./types";

export const conferencePlans: PricingPlan[] = [
  {
    packageId: 'scl-eb',
    title: 'School Students & School Leavers',
    price: 1500,
    originalPrice: 2000,
    currency: 'Rs.',
    features: [
      { text: 'Full YSF Access' },
      { text: 'Lunch Included' },
      { text: 'Transportation is available for an additional fee of Rs. 500' },
    ],
    badge: 'Early Bird! *',
    badgeColor: 'red',
    buttonText: 'SELECT',
  },
  {
    packageId: 'uni-eb',
    title: 'Undergraduates',
    price: 2000,
    originalPrice: 2500,
    currency: 'Rs.',
    features: [
      { text: 'Full YSF Access' },
      { text: 'Lunch Included' },
      { text: 'Transportation is available for an additional fee of Rs. 500' },
    ],
    badge: 'Early Bird! *',
    badgeColor: 'red',
    buttonText: 'SELECT',
  },
  {
    packageId: 'corp-eb',
    title: 'Corporates/Open',
    price: 4000,
    originalPrice: 4500,
    currency: 'Rs.',
    features: [
      { text: 'Full YSF Access' },
      { text: 'Lunch Included' },
      { text: 'Transportation Included' },
    ],
    badge: 'Early Bird! *',
    badgeColor: 'red',
    buttonText: 'SELECT',
    highlighted: true,
  },
  {
    packageId: 'scl-b-eb',
    title: 'School Students & School Leavers',
    price: 1300,
    originalPrice: 1800,
    currency: 'Rs.',
    features: [{ text: 'For 10+ participants' }, { text: 'From same school' }],
    badge: 'Bulk Offer! *',
    badgeColor: 'green',
    buttonText: 'SELECT',
  },
  {
    packageId: 'uni-b-eb',
    title: 'Undergraduates',
    price: 1800,
    originalPrice: 2300,
    currency: 'Rs.',
    features: [{ text: 'For 10+ participants' }, { text: 'From same university' }],
    badge: 'Bulk Offer! *',
    badgeColor: 'green',
    buttonText: 'SELECT',
  },
  {
    packageId: 'corp-b-eb',
    title: 'Corporates/Open',
    price: 3800,
    originalPrice: 4300,
    currency: 'Rs.',
    features: [{ text: 'For 10+ participants' }, { text: 'From same company' }],
    badge: 'Bulk Offer! *',
    badgeColor: 'green',
    buttonText: 'SELECT',
  },
];