const timeSlots = [
  '07:00 - 07:15',
  '07:15 - 07:30',
  '07:30 - 07:45',
  '07:45 - 08:00',
  '08:00 - 08:15',
  '08:15 - 08:30',
  '08:30 - 08:45',
  '08:45 - 09:00',
  '09:00 - 09:15',
  '09:15 - 09:30',
  '09:30 - 09:45',
  '09:45 - 10:00',
  '10:00 - 10:15',
  '10:15 - 10:30',
  '10:30 - 10:45',
  '10:45 - 11:00',
  '11:00 - 11:15',
  '11:15 - 11:30',
  '11:30 - 11:45',
  '11:45 - 12:00',
  '12:00 - 12:15',
  '12:15 - 12:30',
  '12:30 - 12:45',
  '12:45 - 13:00',
  '13:00 - 13:15',
  '13:15 - 13:30',
  '13:30 - 13:45',
  '13:45 - 14:00',
  '14:00 - 14:15',
  '14:15 - 14:30',
  '14:30 - 14:45',
  '14:45 - 15:00',
  '15:00 - 15:15',
  '15:15 - 15:30',
  '15:30 - 15:45',
  '15:45 - 16:00',
  '16:00 - 16:15',
  '16:15 - 16:30',
  '16:30 - 16:45',
  '16:45 - 17:00',
  '17:00 - 17:15',
  '17:15 - 17:30',
  '17:30 - 17:45',
  '17:45 - 18:00',
  '18:00 - 18:15',
  '18:15 - 18:30',
  '18:30 - 18:45',
  '18:45 - 19:00',
  '19:00 - 19:15',
  '19:15 - 19:30',
  '19:30 - 19:45',
  '19:45 - 20:00',
  '20:00 - 20:15',
  '20:15 - 20:30',
  '20:30 - 20:45',
  '20:45 - 21:00',
  '21:00 - 21:15',
  '21:15 - 21:30',
  '21:30 - 21:45',
  '21:45 - 22:00',
  '22:00 - 22:15',
  '22:15 - 22:30',
  '22:30 - 22:45',
  '22:45 - 23:00',
  '23:00 - 23:15',
  '23:15 - 23:30',
  '23:30 - 23:45',
  '23:45 - 00:00',
];

export const agendaData = {
  day0: {
    title: 'Day 0 - The 150',
    date: '05-Jul',
    description: 'MCP Day',
    color: 'blue',
    tracks: ['MCP'],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'MCP Checkin',
        targetRoles: ['MCP'],
        startTime: '09:00',
        endTime: '11:30',
        type: 'break',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '11:30',
        endTime: '13:00',
        type: 'break',
      },
      {
        title: 'MCP Opening Plenary',
        targetRoles: ['MCP'],
        startTime: '13:00',
        endTime: '14:00',
        type: 'plenary',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '14:00',
        endTime: '14:15',
        type: 'break',
      },
      {
        title: 'Role of Presidents in IC - the 150',
        targetRoles: ['MCP'],
        startTime: '14:15',
        endTime: '14:45',
      },
      {
        title: 'LEAD',
        targetRoles: ['MCP'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '15:45',
        endTime: '16:00',
        type: 'break',
      },
      {
        title: 'Regional Spaces',
        targetRoles: ['MCP'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '17:00',
        endTime: '17:15',
        type: 'break',
      },
      {
        title: 'Unstoppable Talks',
        targetRoles: ['MCP'],
        startTime: '17:15',
        endTime: '18:30',
      },
      {
        title: 'MCP Evening Plenary',
        targetRoles: ['MCP'],
        startTime: '18:30',
        endTime: '19:15',
        type: 'plenary',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '19:15',
        endTime: '20:15',
        type: 'break',
      },
      {
        title: 'Lego Fair',
        targetRoles: ['MCP'],
        startTime: '20:15',
        endTime: '22:15',
      },
      {
        title: 'Welcome Party',
        targetRoles: ['MCP'],
        startTime: '22:15',
        endTime: '23:59',
      },
    ],
  },
  day1: {
    title: 'Day 1 - Power of Us',
    date: '06-Jul',
    description: 'IC Opening | PAI Elections',
    color: 'yellow',
    tracks: ['All'],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast + Check-in',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '09:00',
        type: 'break',
      },
      {
        title: 'Check-in',
        targetRoles: ['All'],
        startTime: '09:00',
        endTime: '09:30',
        type: 'break',
      },
      {
        title: 'Ushering',
        targetRoles: ['All'],
        startTime: '09:30',
        endTime: '10:00',
        type: 'break',
      },
      {
        title: 'Opening Ceremony',
        targetRoles: ['All'],
        startTime: '10:00',
        endTime: '12:00',
        type: 'special event',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '12:00',
        endTime: '14:00',
        type: 'break',
      },
      {
        title: 'Opening Plenary + Opening of IC 2025',
        targetRoles: ['All'],
        startTime: '14:00',
        endTime: '16:15',
        type: 'plenary',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '16:15',
        endTime: '16:30',
        type: 'break',
      },
      {
        title: 'Essence',
        targetRoles: ['All'],
        startTime: '16:30',
        endTime: '18:00',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '18:00',
        endTime: '18:30',
        type: 'break',
      },
      {
        title: 'PAI Elections Briefing',
        targetRoles: ['All'],
        startTime: '18:30',
        endTime: '19:00',
        type: 'pai election',
      },
      {
        title: 'PAI Elections Opening Speeches',
        targetRoles: ['All'],
        startTime: '19:00',
        endTime: '20:45',
        type: 'pai election',
      },
      {
        title: 'DHL Networking Space',
        targetRoles: ['All'],
        startTime: '20:45',
        endTime: '21:30',
        type: 'networking',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '21:30',
        endTime: '22:30',
        type: 'break',
      },
      {
        title: 'Chill Night',
        targetRoles: ['All'],
        startTime: '22:30',
        endTime: '23:59',
      },
    ],
  },
  day2: {
    title: 'Day 2 - Power of You',
    date: '07-Jul',
    description: 'PAI Election',
    color: 'red',
    tracks: ['MCP', 'LCP', 'LCVP', 'MCVP', 'Alumni'],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '08:45',
        type: 'break',
      },
      {
        title: 'Roll calls',
        targetRoles: ['All'],
        startTime: '08:45',
        endTime: '09:00',
        type: 'break',
      },
      {
        title: 'Morning Plenary',
        targetRoles: ['LCVP', 'LCP', 'MCVP', 'Alumni'],
        startTime: '09:00',
        endTime: '10:15',
        type: 'plenary',
      },
      {
        title: 'Election QnA',
        targetRoles: ['MCP'],
        startTime: '09:00',
        endTime: '11:30',
        type: 'pai election',
      },
      {
        title: 'Break',
        targetRoles: ['LCVP', 'LCP', 'MCVP', 'Alumni'],
        startTime: '10:15',
        endTime: '10:30',
        type: 'break',
      },
      {
        title: 'Power of You',
        targetRoles: ['LCVP', 'LCP', 'MCVP', 'Alumni'],
        startTime: '10:30',
        endTime: '11:30',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '11:30',
        endTime: '11:45',
        type: 'break',
      },
      {
        title: 'DHL Keynote',
        targetRoles: ['All'],
        startTime: '11:45',
        endTime: '12:30',
        type: 'keynote',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '12:30',
        endTime: '13:45',
        type: 'break',
      },
      {
        title: 'External Panel',
        targetRoles: ['All'],
        startTime: '13:45',
        endTime: '15:15',
        type: 'pai election',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '15:15',
        endTime: '15:30',
        type: 'break',
      },
      {
        title: 'Closing Speeches',
        targetRoles: ['All'],
        startTime: '15:30',
        endTime: '17:30',
        type: 'pai election',
      },
      {
        title: 'Break',
        targetRoles: ['MCP'],
        startTime: '17:30',
        endTime: '17:45',
        type: 'break',
      },
      {
        title: 'Break',
        targetRoles: ['LCVP', 'LCP', 'MCVP', 'Alumni'],
        startTime: '17:30',
        endTime: '18:15',
        type: 'break',
      },
      {
        title: 'Voting',
        targetRoles: ['MCP'],
        startTime: '17:45',
        endTime: '19:15',
        type: 'pai election',
      },
      {
        title: 'LEAD',
        targetRoles: ['MCVP'],
        startTime: '18:15',
        endTime: '19:15',
      },
      {
        title: 'LEAD',
        targetRoles: ['LCP'],
        startTime: '18:15',
        endTime: '19:15',
      },
      {
        title: 'LEAD',
        targetRoles: ['LCVP'],
        startTime: '18:15',
        endTime: '19:15',
      },
      {
        title: 'LEAD',
        targetRoles: ['Alumni'],
        startTime: '18:15',
        endTime: '19:15',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '19:15',
        endTime: '20:15',
        type: 'break',
      },
      {
        title: 'Global Village Preparation 1 - Chief Delegates (stalls)',
        targetRoles: ['All'],
        startTime: '20:15',
        endTime: '20:30',
        type: 'break',
      },
      {
        title: 'PAI Announcement',
        targetRoles: ['All'],
        startTime: '20:30',
        endTime: '21:30',
        type: 'pai election',
      },
      {
        title: 'Global Village Preparation 2 (dressup)',
        targetRoles: ['All'],
        startTime: '21:30',
        endTime: '22:00',
        type: 'break',
      },
      {
        title: 'Global Village',
        targetRoles: ['All'],
        startTime: '22:00',
        endTime: '23:59',
        type: 'special event',
      },
    ],
  },
  day3: {
    title: 'Day 3 - Power of AIESEC',
    date: '08-Jul',
    description: 'Conference Start | Sri Lankan Night',
    color: 'green',
    tracks: [
      'MCP',
      'LCP',
      'LCVP',
      'MCVP GV',
      'MCVP GT',
      'MCVP MXP/OD',
      'MCVP FIN',
      'MCVP BD/EwA/PR',
      'MCVP MKT',
      'Alumni',
    ],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '08:45',
        type: 'break',
      },
      {
        title: 'Roll calls',
        targetRoles: ['All'],
        startTime: '08:45',
        endTime: '09:00',
        type: 'break',
      },
      {
        title: 'Morning Plenary',
        targetRoles: ['All'],
        startTime: '09:00',
        endTime: '10:15',
        type: 'plenary',
      },
      {
        title: 'Current State',
        targetRoles: ['All'],
        startTime: '10:15',
        endTime: '11:15',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '11:15',
        endTime: '11:30',
        type: 'break',
      },
      {
        title: 'First 90 days',
        targetRoles: ['MCP'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'LCP / LCVP Checkin',
        targetRoles: ['LCP', 'LCVP'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'GV Checkin',
        targetRoles: ['MCVP GV'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'GT Checkin',
        targetRoles: ['MCVP GT'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'MXP / OD Checkin',
        targetRoles: ['MCVP MXP', 'MCVP OD'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'Fin Checkin',
        targetRoles: ['MCVP FIN'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'BD / EwA / PR Checkin',
        targetRoles: ['MCVP BD', 'MCVP EwA', 'MCVP PR'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'MKT Checkin',
        targetRoles: ['MCVP MKT'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'Alumni Checkin',
        targetRoles: ['Alumni'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '12:30',
        endTime: '14:00',
        type: 'break',
      },
      {
        title: 'ICB | How to work with Audit and Customer Support',
        targetRoles: ['MCP'],
        startTime: '14:00',
        endTime: '15:00',
      },
      {
        title: 'Data Driven Leader',
        targetRoles: ['LCP', 'LCVP'],
        startTime: '14:00',
        endTime: '15:00',
      },
      {
        title: 'ICB | Crisis Management',
        targetRoles: ['MCVP'],
        startTime: '14:00',
        endTime: '15:00',
      },
      {
        title: '24.25 Review the Leader before and after AIESEC',
        targetRoles: ['Alumni'],
        startTime: '14:00',
        endTime: '15:00',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '15:00',
        endTime: '15:15',
        type: 'break',
      },
      {
        title: 'Beyond the JD: The Roles We Really Play',
        targetRoles: ['MCP', 'LCP'],
        startTime: '15:15',
        endTime: '16:15',
      },
      {
        title: 'Where It All Happens: Power of the Operational Level',
        targetRoles: ['LCVP'],
        startTime: '15:15',
        endTime: '16:15',
      },
      {
        title: 'Winning Network',
        targetRoles: ['MCVP'],
        startTime: '15:15',
        endTime: '16:15',
      },
      {
        title: 'Handover',
        targetRoles: ['Alumni'],
        startTime: '15:15',
        endTime: '16:15',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '16:15',
        endTime: '16:30',
        type: 'break',
      },
      {
        title: 'LC Vision',
        targetRoles: ['LCP', 'LCVP'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'Exhchage x BO Synergy',
        targetRoles: ['MCVP GV'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'Exhchage x BO Synergy',
        targetRoles: ['MCVP GT'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'MX / OD for Exchange',
        targetRoles: ['MCVP MXP', 'MCVP OD'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'FIN for Exchange',
        targetRoles: ['MCVP FIN'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'BD / EwA / PR for Exchange',
        targetRoles: ['MCVP BD', 'MCVP EwA', 'MCVP PR'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'MKT for Exchange',
        targetRoles: ['MCVP MKT'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'Personal Portfolio',
        targetRoles: ['Alumni'],
        startTime: '16:30',
        endTime: '17:30',
      },
      {
        title: 'Break',
        targetRoles: ['LCP', 'LCVP', 'MCVP', 'Alumni'],
        startTime: '17:30',
        endTime: '18:00',
        type: 'break',
      },
      {
        title: 'Evening Plenary',
        targetRoles: ['LCP', 'LCVP', 'MCVP', 'Alumni'],
        startTime: '18:00',
        endTime: '19:30',
        type: 'plenary',
      },
      {
        title: 'Evening Plenary',
        targetRoles: ['MCP'],
        startTime: '18:45',
        endTime: '19:30',
        type: 'plenary',
      },
      {
        title: 'Legislation',
        targetRoles: ['MCP'],
        startTime: '16:30',
        endTime: '18:45',
      },
      {
        title: 'WLL Prep',
        targetRoles: ['All'],
        startTime: '19:30',
        endTime: '20:15',
        type: 'wll',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '20:15',
        endTime: '21:15',
        type: 'break',
      },
      {
        title: 'Preparation Time',
        targetRoles: ['All'],
        startTime: '21:15',
        endTime: '21:30',
        type: 'break',
      },
      {
        title: 'Sri Lankan Night',
        targetRoles: ['All'],
        startTime: '21:30',
        endTime: '23:59',
        type: 'special event',
      },
    ],
  },
  day4: {
    title: 'Day 4 - Power of the Future',
    date: '09-Jul',
    description: 'WLL | A2030 Day',
    color: 'lime',
    tracks: ['All'],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '08:00',
        type: 'break',
      },
      {
        title: 'EFF Keynote',
        targetRoles: ['All'],
        startTime: '08:00',
        endTime: '09:00',
        type: 'keynote',
      },
      {
        title: 'Travel to School',
        targetRoles: ['All'],
        startTime: '09:00',
        endTime: '10:00',
        type: 'break',
      },
      {
        title: 'Assembly',
        targetRoles: ['All'],
        startTime: '10:00',
        endTime: '10:30',
        type: 'wll',
      },
      {
        title: 'Ushering',
        targetRoles: ['All'],
        startTime: '10:30',
        endTime: '10:45',
        type: 'wll',
      },
      {
        title: 'WLL',
        targetRoles: ['All'],
        startTime: '10:45',
        endTime: '11:45',
        type: 'wll',
      },
      {
        title: 'Post Event',
        targetRoles: ['All'],
        startTime: '11:45',
        endTime: '12:15',
        type: 'wll',
      },
      {
        title: 'Travel to Citrus',
        targetRoles: ['All'],
        startTime: '12:15',
        endTime: '13:00',
        type: 'break',
      },
      {
        title: 'Debrief',
        targetRoles: ['All'],
        startTime: '13:00',
        endTime: '13:30',
        type: 'wll',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '13:30',
        endTime: '14:45',
        type: 'break',
      },
      {
        title: 'A2030 Launch',
        targetRoles: ['All'],
        startTime: '14:45',
        endTime: '15:15',
        type: 'a2030',
      },
      {
        title: 'A2030 MTA Launch',
        targetRoles: ['All'],
        startTime: '15:15',
        endTime: '15:45',
        type: 'a2030',
      },
      {
        title: 'A2030 Behind the Scenes',
        targetRoles: ['All'],
        startTime: '15:45',
        endTime: '16:15',
        type: 'a2030',
      },
      {
        title: "Let's hear from...",
        targetRoles: ['All'],
        startTime: '16:15',
        endTime: '16:30',
        type: 'a2030',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '16:30',
        endTime: '16:45',
        type: 'break',
      },
      {
        title: 'From Past to Future',
        targetRoles: ['All'],
        startTime: '16:45',
        endTime: '17:30',
        type: 'a2030',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '17:30',
        endTime: '17:45',
        type: 'break',
      },
      {
        title: 'Regional Dreaming',
        targetRoles: ['All'],
        startTime: '17:45',
        endTime: '18:15',
        type: 'a2030',
      },
      {
        title: 'Entity Dreaming',
        targetRoles: ['All'],
        startTime: '18:15',
        endTime: '18:45',
        type: 'a2030',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '18:45',
        endTime: '19:00',
        type: 'break',
      },
      {
        title: 'How to Communicate A2030',
        targetRoles: ['All'],
        startTime: '19:00',
        endTime: '19:30',
        type: 'a2030',
      },
      {
        title: 'Evening Plenary',
        targetRoles: ['All'],
        startTime: '19:30',
        endTime: '20:30',
        type: 'plenary',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '20:30',
        endTime: '21:30',
        type: 'break',
      },
      {
        title: 'Entity Time',
        targetRoles: ['All'],
        startTime: '21:30',
        endTime: '22:00',
      },
      {
        title: 'A2030 Party',
        targetRoles: ['All'],
        startTime: '22:00',
        endTime: '23:59',
        type: 'a2030',
      },
    ],
  },
  day5: {
    title: 'Day 5 - Exchange and Relevance',
    date: '10-Jul',
    description: 'YSF | Partners Day',
    color: 'grape',
    tracks: ['Employability', 'Leadership', 'Sustainability', 'Diversity'],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast + Local Delegate Check-in',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '09:00',
        type: 'break',
      },
      {
        title: 'Opening Youth Speak Forum',
        targetRoles: ['All'],
        startTime: '09:00',
        endTime: '09:30',
        type: 'ysf',
      },
      {
        title: 'Panel Discussion A | UN Foundation, UNICEF, JCI',
        targetRoles: ['Employability', 'Leadership'],
        startTime: '09:30',
        endTime: '10:15',
        type: 'ysf',
      },
      {
        title: 'Panel Discussion B | Project Everyone, UNIDO, EFF',
        targetRoles: ['Sustainability', 'Diversity'],
        startTime: '09:30',
        endTime: '10:15',
        type: 'ysf',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '10:15',
        endTime: '10:30',
        type: 'break',
      },
      {
        title: 'Employabiliy | Electrolux',
        targetRoles: ['All'],
        startTime: '10:30',
        endTime: '11:00',
        type: 'keynote',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '11:00',
        endTime: '11:15',
        type: 'break',
      },
      {
        title: 'Workshop | Mastercard',
        targetRoles: ['Employability'],
        startTime: '11:15',
        endTime: '12:15',
        type: 'workshop',
      },
      {
        title: 'Leadership Reimagined | DHL',
        targetRoles: ['Leadership'],
        startTime: '11:15',
        endTime: '12:15',
        type: 'workshop',
      },
      {
        title: 'Workshop | JCI',
        targetRoles: ['Sustainability'],
        startTime: '11:15',
        endTime: '12:15',
        type: 'workshop',
      },
      {
        title: 'Workshop | Nagarro',
        targetRoles: ['Diversity'],
        startTime: '11:15',
        endTime: '12:15',
        type: 'workshop',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '12:15',
        endTime: '12:30',
        type: 'break',
      },
      {
        title: 'Employabiliy | PwC',
        targetRoles: ['All'],
        startTime: '12:30',
        endTime: '13:15',
        type: 'keynote',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '13:15',
        endTime: '14:30',
        type: 'break',
      },
      {
        title: 'Keynote | TCS',
        targetRoles: ['All'],
        startTime: '14:30',
        endTime: '15:15',
        type: 'keynote',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '15:15',
        endTime: '15:30',
        type: 'break',
      },
      {
        title: 'Workshop Employability | PwC',
        targetRoles: ['Employability'],
        startTime: '15:30',
        endTime: '16:30',
        type: 'workshop',
      },
      {
        title: 'Workshop | Henkel',
        targetRoles: ['Leadership'],
        startTime: '15:30',
        endTime: '16:30',
        type: 'workshop',
      },
      {
        title: 'Entrepreneurship & Innovation for Social Sustainability | DHL',
        targetRoles: ['Sustainability'],
        startTime: '15:30',
        endTime: '16:30',
        type: 'workshop',
      },
      {
        title: 'Workshop | TCS',
        targetRoles: ['Diversity'],
        startTime: '15:30',
        endTime: '16:30',
        type: 'workshop',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '16:30',
        endTime: '16:45',
        type: 'break',
      },
      {
        title: 'The Daring Challenge | Henkel',
        targetRoles: ['All'],
        startTime: '16:45',
        endTime: '17:15',
        type: 'keynote',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '17:15',
        endTime: '17:30',
        type: 'break',
      },
      {
        title:
          'A Shared Vision: Transforming Youth Employability through Partnerships Keynote | DHL',
        targetRoles: ['All'],
        startTime: '17:30',
        endTime: '18:00',
        type: 'keynote',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '18:00',
        endTime: '18:30',
        type: 'break',
      },
      {
        title: 'Networking Space',
        targetRoles: ['All'],
        startTime: '18:30',
        endTime: '19:30',
        type: 'networking',
      },
      {
        title: 'Keynote - UNIDO',
        targetRoles: ['All'],
        startTime: '19:30',
        endTime: '20:00',
        type: 'keynote',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '20:00',
        endTime: '20:15',
        type: 'break',
      },
      {
        title: 'Closing',
        targetRoles: ['All'],
        startTime: '20:15',
        endTime: '20:30',
        type: 'ysf',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '20:30',
        endTime: '22:00',
        type: 'break',
      },
      {
        title: 'Regional Parties',
        targetRoles: ['All'],
        startTime: '22:00',
        endTime: '23:59',
      },
    ],
  },
  day6: {
    title: 'Day 6 - Exchange and Growth',
    date: '11-Jul',
    description: 'Functional Day | Gala Night',
    color: 'indigo',
    tracks: [
      'MCP',
      'LCP',
      'LCVP',
      'MCVP GV',
      'MCVP GT',
      'MCVP MXP/OD',
      'MCVP FIN',
      'MCVP BD/EwA/PR',
      'MCVP MKT',
      'Alumni',
    ],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '08:30',
        type: 'break',
      },
      {
        title: 'Roll Calls',
        targetRoles: ['All'],
        startTime: '08:30',
        endTime: '08:45',
        type: 'break',
      },
      {
        title: 'Morning Plenary',
        targetRoles: ['All'],
        startTime: '08:45',
        endTime: '10:15',
        type: 'plenary',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '10:15',
        endTime: '10:30',
        type: 'break',
      },
      {
        title: 'All about OD',
        targetRoles: ['All'],
        startTime: '10:30',
        endTime: '11:15',
      },
      {
        title: 'Electrolux Booth',
        targetRoles: ['All'],
        startTime: '11:15',
        endTime: '11:45',
      },
      {
        title: 'A2030 for MCPs',
        targetRoles: ['MCP'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for LCPs',
        targetRoles: ['LCP'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'Same as MCVPs',
        targetRoles: ['LCVP'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for GV',
        targetRoles: ['MCVP GV'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for GT',
        targetRoles: ['MCVP GT'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for FIN',
        targetRoles: ['MCVP FIN'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for MKT',
        targetRoles: ['MCVP MKT'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for MX / OD',
        targetRoles: ['MCVP MXP', 'MCVP OD'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'A2030 for BD / EwA / PR',
        targetRoles: ['MCVP BD', 'MCVP EwA', 'MCVP PR'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'From Youth to Global Citizen',
        targetRoles: ['Alumni'],
        startTime: '11:45',
        endTime: '12:30',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '12:30',
        endTime: '13:45',
        type: 'break',
      },
      {
        title: 'Using Technology for Growth',
        targetRoles: ['MCP'],
        startTime: '13:45',
        endTime: '14:30',
      },
      {
        title: 'Using Technology for Growth',
        targetRoles: ['MCVP', 'LCVP', 'Alumni'],
        startTime: '13:45',
        endTime: '14:30',
      },
      {
        title: 'Building a Performance Driven Entity',
        targetRoles: ['LCP'],
        startTime: '13:45',
        endTime: '14:30',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '14:30',
        endTime: '14:45',
        type: 'break',
      },
      {
        title: 'Building a performance driven MC',
        targetRoles: ['MCP'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'LC2LC IR',
        targetRoles: ['LCP', 'LCVP'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'RE Management',
        targetRoles: ['MCVP GV'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'RE Management',
        targetRoles: ['MCVP GT'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'HR Lifespan: How to Retain People',
        targetRoles: ['MCVP MXP', 'MCVP OD'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'Building a strong Finance Culture',
        targetRoles: ['MCVP FIN'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'Building a performance driven MC',
        targetRoles: ['MCP'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'Cosales and working with AI',
        targetRoles: ['MCVP BD', 'MCVP EwA'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'How to do PR',
        targetRoles: ['MCVP MKT/PR'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'PAIe Vision',
        targetRoles: ['Alumni'],
        startTime: '14:45',
        endTime: '15:45',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '15:45',
        endTime: '16:00',
        type: 'break',
      },
      {
        title: 'Cluster 1',
        targetRoles: ['MCP', 'LCP'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Cluster 2',
        targetRoles: ['LCVP', 'MCVP GV'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Cluster 3',
        targetRoles: ['MCVP GT', 'MCVP MXP', 'MCVP OD'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Cluster 4',
        targetRoles: ['MCVP FIN', 'MCVP BD', 'MCVP EwA', 'MCVP PR'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Cluster 5',
        targetRoles: ['MCVP MKT'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Career Acceleration after AIESEC',
        targetRoles: ['Alumni'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Evening Plenary',
        targetRoles: ['All'],
        startTime: '17:00',
        endTime: '18:45',
        type: 'plenary',
      },
      {
        title: 'Prep Time',
        targetRoles: ['All'],
        startTime: '18:45',
        endTime: '21:15',
        type: 'break',
      },
      {
        title: 'Gala Dinner',
        targetRoles: ['All'],
        startTime: '21:15',
        endTime: '22:00',
        type: 'special event',
      },
      {
        title: 'Gala Night',
        targetRoles: ['All'],
        startTime: '22:00',
        endTime: '23:59',
        type: 'special event',
      },
    ],
  },
  day7: {
    title: 'Day 7 - Exchange and Leadership',
    date: '12-Jul',
    description: 'Functional Day | Regional Parties',
    color: 'cyan',
    tracks: [
      'MCP',
      'LCP',
      'LCVP',
      'MCVP GV',
      'MCVP GT',
      'MCVP MXP/OD',
      'MCVP FIN',
      'MCVP BD/EwA/PR',
      'MCVP MKT',
      'Alumni',
    ],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '08:30',
        type: 'break',
      },
      {
        title: 'Roll Calls',
        targetRoles: ['All'],
        startTime: '08:30',
        endTime: '09:00',
        type: 'break',
      },
      {
        title: 'Morning Plenary',
        targetRoles: ['All'],
        startTime: '09:00',
        endTime: '10:00',
        type: 'plenary',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '10:00',
        endTime: '10:15',
        type: 'break',
      },
      {
        title: 'We Fight Bugs',
        targetRoles: ['MCP', 'MCVP', 'LCP', 'LCVP'],
        startTime: '10:15',
        endTime: '11:15',
      },
      {
        title: 'Alumni & Beyond',
        targetRoles: ['Alumni'],
        startTime: '10:15',
        endTime: '11:15',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '11:15',
        endTime: '11:30',
        type: 'break',
      },
      {
        title: 'Regional Spaces',
        targetRoles: ['All'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'Lunch',
        targetRoles: ['All'],
        startTime: '12:30',
        endTime: '13:45',
        type: 'break',
      },
      {
        title: 'ELD Launches',
        targetRoles: ['All'],
        startTime: '13:45',
        endTime: '14:45',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '14:45',
        endTime: '15:00',
        type: 'break',
      },
      {
        title: 'Radical Candor',
        targetRoles: ['MCP', 'LCP'],
        startTime: '15:00',
        endTime: '16:00',
      },
      {
        title: 'Performance Conversations',
        targetRoles: ['LCVP'],
        startTime: '15:00',
        endTime: '16:00',
      },
      {
        title: 'Leadership Through Trust and Failure',
        targetRoles: ['MCP', 'LCP'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Beyond the LCVP Title',
        targetRoles: ['LCVP'],
        startTime: '16:00',
        endTime: '17:00',
      },
      {
        title: 'Elephant in the Room',
        targetRoles: ['MCVP GV'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'Elephant in the Room',
        targetRoles: ['MCVP GT'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'Elephant in the Room',
        targetRoles: ['MCVP FIN'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'Elephant in the Room',
        targetRoles: ['MCVP MXP', 'MCVP OD'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'Elephant in the Room',
        targetRoles: ['MCVP BD', 'MCVP EwA', 'MCVP PR'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'Elephant in the Room',
        targetRoles: ['MCVP MKT'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'The Unwritten Lessons',
        targetRoles: ['Alumni'],
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '17:00',
        endTime: '17:15',
        type: 'break',
      },
      {
        title: 'BIM Launch',
        targetRoles: ['All'],
        startTime: '17:15',
        endTime: '18:15',
      },
      {
        title: 'Evening Plenary',
        targetRoles: ['All'],
        startTime: '18:15',
        endTime: '19:30',
        type: 'plenary',
      },
      {
        title: 'Dinner',
        targetRoles: ['All'],
        startTime: '19:30',
        endTime: '20:30',
        type: 'break',
      },
      {
        title: 'Entity Time',
        targetRoles: ['All'],
        startTime: '20:30',
        endTime: '21:00',
      },
      {
        title: 'AI Party',
        targetRoles: ['All'],
        startTime: '21:00',
        endTime: '23:59',
        type: 'special event',
      },
    ],
  },
  day8: {
    title: 'Day 8 - UNSTOPPABLE Choices',
    date: '13-Jul',
    description: 'IC Closing',
    color: 'pink',
    tracks: [
      'MCP',
      'LCP',
      'LCVP',
      'MCVP GV',
      'MCVP GT',
      'MCVP MXP/OD',
      'MCVP FIN',
      'MCVP BD/EwA/PR',
      'MCVP MKT',
      'Alumni',
    ],
    timeSlots: timeSlots,
    sessions: [
      {
        title: 'Breakfast / Checkout',
        targetRoles: ['All'],
        startTime: '07:00',
        endTime: '08:30',
        type: 'break',
      },
      {
        title: 'Roll Calls',
        targetRoles: ['All'],
        startTime: '08:30',
        endTime: '09:00',
        type: 'break',
      },
      {
        title: 'Morning Plenary',
        targetRoles: ['All'],
        startTime: '09:00',
        endTime: '10:00',
        type: 'plenary',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '10:00',
        endTime: '10:15',
        type: 'break',
      },
      {
        title: 'PAI / PAIe Space',
        targetRoles: ['All'],
        startTime: '10:15',
        endTime: '11:15',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '11:15',
        endTime: '11:30',
        type: 'break',
      },
      {
        title: 'MCP Closing',
        targetRoles: ['MCP'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'LCP / LCVP Closing',
        targetRoles: ['LCP', 'LCVP'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'GV Closing',
        targetRoles: ['MCVP GV'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'GT Closing',
        targetRoles: ['MCVP GT'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'MX / OD Closing',
        targetRoles: ['MCVP MXP', 'MCVP OD'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'FIN Closing',
        targetRoles: ['MCVP FIN'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'BD / EwA / PR Closing',
        targetRoles: ['MCVP BD', 'MCVP EwA', 'MCVP PR'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'MKT Closing',
        targetRoles: ['MCVP MKT'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'The AIESEC Ripple Effect',
        targetRoles: ['Alumni'],
        startTime: '11:30',
        endTime: '12:30',
      },
      {
        title: 'Lunch & Checkout',
        targetRoles: ['All'],
        startTime: '12:30',
        endTime: '13:45',
        type: 'break',
      },
      {
        title: 'Unstoppable AIESEC',
        targetRoles: ['All'],
        startTime: '13:45',
        endTime: '14:45',
      },
      {
        title: 'Break',
        targetRoles: ['All'],
        startTime: '14:45',
        endTime: '15:00',
        type: 'break',
      },
      {
        title: 'Closing Plenary',
        targetRoles: ['All'],
        startTime: '15:00',
        endTime: '17:00',
        type: 'plenary',
      },
    ],
  },
};
