import { TeamMember } from '@/app/(portal)/contact/(components)/types';

export const dxTeam: TeamMember[] = [
  {
    id: '1',
    name: 'Ameera Izmie',
    position: 'CCVP Delegates Experience',
    email: 'ameera.izmie@aiesec.net',
    phone: '+94 77 630 3724',
    telegram: 'ameera_izmie',
  },
  {
    id: '2',
    name: 'Didulanka Gamage',
    position: 'DX Specialist',
    email: 'didulanka.gamage@aiesec.net',
    phone: '+94 77 379 9736',
    telegram: 'didu_g',
  },
  {
    id: '3',
    name: 'Binuri Perera',
    position: 'DX Team Leader',
    email: 'binuri.perera@aiesec.net',
    phone: '+94 76 351 5551',
    telegram: 'Binuri_01',
  },
  {
    id: '4',
    name: 'Sasith Kawshalya',
    position: 'DX Team Leader',
    email: 'sasith.kawshalya@aiesec.net',
    phone: '+94 74 342 0040',
    telegram: 'sasith_kawshalya_1',
  },
  {
    id: '5',
    name: 'Chanuli Indigahawela',
    position: 'DX Coordinator',
    email: 'chanuli.indigahawela@aiesec.net',
    phone: '+94 71 204 4353',
    telegram: 'chanuli_27',
  },
  {
    id: '6',
    name: 'Jayathree Wijewardana',
    position: 'DX Coordinator',
    email: 'jayathri.wij@aiesec.net',
    phone: '+94 76 131 6724',
    telegram: 'JayathriW',
  },
  {
    id: '7',
    name: 'Lahirunie Dulsara',
    position: 'DX Coordinator',
    email: 'lahirunie.dulsara@aiesec.net',
    phone: '+94 76 698 6042',
    telegram: 'lahi_dul',
  },
  {
    id: '8',
    name: 'Pehan Ransika',
    position: 'DX Coordinator',
    email: 'pehan.ransika@aiesec.net',
    phone: '+94 71 874 0792',
    telegram: 'pehan_r',
  },
];

export const coreTeam: TeamMember[] = [
  {
    id: '1',
    name: 'Bhagya Ranasinghe',
    position: 'Congress Committee President',
    email: 'bhagya.ranasinghe@aiesec.net',
    phone: '+94 71 876 5432',
    telegram: 'bhagya_ranasinghe',
  },
  {
    id: '2',
    name: 'Ameera Izmie',
    position: 'CCVP Delegates Experience',
    email: 'ameera.izmie@aiesec.net',
    phone: '+94 77 630 3724',
    telegram: 'ameera_izmie',
  },
  {
    id: '3',
    name: 'Sadeesha Sathmina',
    position: 'CCVP Finance',
    email: 'sadeesha.sathmina@aiesec.net',
    phone: '+94 76 451 9607',
    telegram: 'sadeesha01',
  },
  {
    id: '4',
    name: 'Dyon De Heodt',
    position: 'CCVP Business Development',
    email: 'dyon.walter@aiesec.net',
    phone: '+94 77 182 3826',
    telegram: 'dyonwalter',
  },
  {
    id: '5',
    name: 'Shashini Dilsara',
    position: 'CCVP Human Resources',
    email: 'shashini.dilsara@aiesec.net',
    phone: '+94 71 554 1323',
    telegram: 'shashinid99',
  },
  {
    id: '6',
    name: 'Ashan Subodha',
    position: 'CCVP Logistics',
    email: 'ashan.subodha@aiesec.net',
    phone: '+94 71 490 2057',
    telegram: 'ashaneo1',
  },
  {
    id: '7',
    name: 'Nisanya Pathirana',
    position: 'CCVP Special Events & PR',
    email: 'nisanya.pathirana@aiesec.net',
    phone: '+94 77 242 6488',
    telegram: 'nisanya_pathirana',
  },
  {
    id: '8',
    name: 'Nishith Pinnawala',
    position: 'CCVP Marketing',
    email: 'nishith.p@aiesec.net',
    phone: '+94 76 679 6797',
    telegram: 'nxnith',
  },
];
